/* this code is generated by tc3bindings\cs_enum_generator.py */
using System;

namespace PLC
{
    namespace Enums
    {
    
        // size = 2B
        public enum ZApplication_ApplicationState : short
        {
            Undefined = 0,
            Boot = 1,
            Running = 2,
            BootFault = 3
        };

    
        // size = 2B
        public enum ZCore_LogLevel : short
        {
            Trace = 0,// < *Zeugwerk Framework* diagnostic messages, this level is reserved for use libraries
            Debug = 1,// < detailed information about key method parameters or other information that is useful for finding likely problems in specific 'problematic' areas of the code
            Info = 2,// < diagnostic messages in production (step changes, method calls, ...)
            Warning = 3,// < errors in sequences that are unusual, but the machine can deal with at least semi-automatically
            Error = 4,// < sequence error that stop the machine from working properly (axes fault, actuator timeouts, invalid data ...)
            Fatal = 5,// < hardware failures, booting sequence failures
            Off = 6// < used to switch off log messages completely when setting a [log-level filter](xref:ZCore.ILogger#SetLevel)
        };

    
        // size = 2B
        public enum ZApplication_AlarmingState : short
        {
            Undefined = 0,
            Incoming = 1,// < an alarm was issued by the PLC
            IncomingAcknowledged = 2,// < the incoming alarm has been acknowledged by an operator or a trigger
            Outgoing = 4,// < the reason why the alarm was issued by the PLC is gone
            OutgoingAcknowledged = 8,// < the disappearance of the alarm reason is acknowledged by the operator or a trigger
            Done = 15// < no user interaction required
        };

    
        // size = 2B
        public enum ZApplication_UnitStateMachineState : short
        {
            Undefined = 0,// < Zero is no valid state and therefore undefined
            Boot = 1,// < Initial state of a unit. It is executed during startup and can also be executed later if necessary to do a reinitialization
            BootFault = 2,// < If booting (e.g. startup) fails, this is indicated by this state; possible errors can be a missing connection to a fieldbus or faulty initialization
            Init = 3,// < Init state is set after booting succeeded, this means the unit is ready for use but needs proper homing
            Idle = 4,// < Idle state signals that the unit is ready for use and is homed properly
            Stopped = 5,// < Signals to a statemachine that has been stopped and the *stop sequence* has been executed
            Fault = 6,// < If anything caused an error in a unit (usually an equipment instance inside the *automatic sequence* or the *homing sequence*) the statemachine takes care of executing a faultreaction and subsequently transitions into the fault state.
            GoHome = 7,// < Active state to bring the unit from an init or faulty state into a homed environment 
            Stop = 8,// < Active state to stop the unit by executing the *stop sequence* 
            FaultReaction = 9,// < Active state to react to a fault which happens during idle state or *automatic sequence*. When the fault reaction is done, the unit is put into its fault state.
            Automatic = 10// < Active state which controls the actual process of the unit
        };

    
        // size = 2B
        public enum ZCore_ObjectState : short
        {
            Booting = 0,// < after starting the PLC all objects are in its booting state and doing initialization stuff, this is represented by Booting
            BootingError = 1,// < if something gets wrong in Booting state, the objects changes to BootingError
            Idle = 2,// < after successfull boot phase, the object is in its idle state and ready for action
            Busy = 3,// < in Busy state the object is doing its supposed work; this is signalized by [_obj.IsBusy()=TRUE](xref:ZCore.Object#IsBusy)
            Error = 4// < if something gets wrong in Busy state, the object changes to error; this is signalized by [_obj.HasError()=TRUE](xref:ZCore.Object#HasError)
        };

    
        // size = 2B
        public enum ZApplication_IoType : short
        {
            Undefined = 0,
            DigitalInput = 1,
            DigitalOutput = 2,
            AnalogInput = 3,
            AnalogOutput = 4,
            Light = 5,
            PulsedOutput = 6,
            DebouncedInput = 7,
            Userdefined = 8
        };

    
    }
}
