/* this code is generated by tc3bindings\cs_enum_generator.py */
using System;

namespace PLC
{
    namespace Enums
    {
    
        // size = 2B
        public enum ZApplication_UnitStateMachineState : short
        {
            Undefined = 0,
            Boot = 1,
            BootFault = 2,
            Init = 3,
            Idle = 4,
            Stopped = 5,
            Fault = 6,
            Gohome = 7,
            Stop = 8,
            FaultReaction = 9,
            Automatic = 10
        };

    
        // size = 2B
        public enum ZCore_ObjectState : short
        {
            Booting = 0,//  after starting the PLC all objects are in its booting state and doing initialization stuff, this is represented by Booting
            BootingError = 1,//  if something gets wrong in Booting state, the objects changes to BootingError
            Idle = 2,//  after successfull boot phase, the object is in its idle state and ready for action
            Busy = 3,//  in Busy state the object is doing its supposed work; this is signalized by [_obj.IsBusy()=TRUE](xref:ZCore.Object#IsBusy)
            Error = 4//  if something gets wrong in Busy state, the object changes to error; this is signalized by [_obj.HasError()=TRUE](xref:ZCore.Object#HasError)
        };

    
        // size = 2B
        public enum ZApplication_IoType : short
        {
            Undefined = 0,
            DigitalInput = 1,
            DigitalOutput = 2,
            AnalogInput = 3,
            AnalogOutput = 4,
            Light = 5,
            PulsedOutput = 6,
            DebouncedInput = 7,
            Userdefined = 8
        };

    
        // size = 2B
        public enum ZCore_LogLevel : short
        {
            Trace = 0,//  *Zeugwerk Framework* diagnostic messages, this level is reserved for use libraries
            Debug = 1,//  detailed information about key method parameters or other information that is useful for finding likely problems in specific 'problematic' areas of the code
            Info = 2,//  diagnostic messages in production (step changes, method calls, ...)
            Warning = 3,//  errors in sequences that are unusual, but the machine can deal with at least semi-automatically
            Error = 4,//  sequence error that stop the machine from working properly (axes fault, actuator timeouts, invalid data ...)
            Fatal = 5,//  hardware failures, booting sequence failures
            Off = 6//  used to switch off log messages completely when setting a [log-level filter](xref:ZAux.Logger#SetLevel)
        };

    
        // size = 2B
        public enum ZApplication_AlarmingState : short
        {
            Undefined = 0,
            Incoming = 1,//  an alarm was issued by the PLC
            IncomingAcknowledged = 2,//  the incoming alarm has been acknowledged by an operator or a trigger
            Outgoing = 4,//  the reason why the alarm was issued by the PLC is gone
            OutgoingAcknowledged = 8,//  the disappearance of the alarm reason is acknowledged by the operator or a trigger
            Done = 15//  no user interaction required
        };

    
    }
}
