/* this code is generated by tc3bindings\cs_struct_generator.py */
using System;
using System.Runtime.InteropServices;
using PLC.Enums;

namespace PLC
{
    namespace Types
    {
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
        public struct String256
        {
            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 256)]
            public string str;
        }
        [StructLayout(LayoutKind.Sequential, CharSet = CharSet.Ansi)]
        public struct String81
        {
            [MarshalAs(UnmanagedType.ByValTStr, SizeConst = 81)]
            public string str;
        } 
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct UselessBoxComRequest
        {
            public byte Start; // offset=0B, size=1B 
            // union in C# have issues with marshaling
            public byte Stop; // offset=1B, size=1B 
            public byte Gohome; // offset=2B, size=1B 
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZEquipment_AxisManualCom
        {
            public byte Supported; // offset=0B, size=1B 
            // union in C# have issues with marshaling
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZEquipment_AxisManualBaseFunctionComPublish
        {
            public ZEquipment_AxisManualCom Extend; // offset=0B, size=1B 
            // union in C# have issues with marshaling
            public String81 Name; // offset=1B, size=81B 
            public String81 Manufacturer; // offset=82B, size=81B 
            public byte IsSimulated; // offset=163B, size=1B 
            public PLC.Enums.ZCore_ObjectState State; // offset=164B, size=2B 
            public byte IsDrivePowered; // offset=166B, size=1B 
            public byte IsDriveEnabled; // offset=167B, size=1B 
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZEquipment_AxisManualHomingComPublish
        {
            public ZEquipment_AxisManualCom Extend; // offset=0B, size=1B 
            // union in C# have issues with marshaling
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZEquipment_AxisManualCurrentComPublish
        {
            public ZEquipment_AxisManualCom Extend; // offset=0B, size=1B 
            // union in C# have issues with marshaling
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 7)] public byte[] _pad0;
            public double ActCurrent; // offset=8B, size=8B 
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZEquipment_AxisManualVelocityComPublish
        {
            public ZEquipment_AxisManualCom Extend; // offset=0B, size=1B 
            // union in C# have issues with marshaling
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 7)] public byte[] _pad0;
            public double ActVelocity; // offset=8B, size=8B 
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZEquipment_AxisManualPositionComPublish
        {
            public ZEquipment_AxisManualCom Extend; // offset=0B, size=1B 
            // union in C# have issues with marshaling
            public byte IsReferenced; // offset=1B, size=1B 
            public short DecimalPlaces; // offset=2B, size=2B 
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)] public byte[] _pad0;
            public double ActPosition; // offset=8B, size=8B 
            public double ActFollowingError; // offset=16B, size=8B 
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZApplication_AxisComPublish
        {
            public ZEquipment_AxisManualBaseFunctionComPublish Base; // offset=0B, size=168B 
            // union in C# have issues with marshaling
            public ZEquipment_AxisManualHomingComPublish Homing; // offset=168B, size=1B 
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 7)] public byte[] _pad0;
            public ZEquipment_AxisManualCurrentComPublish Current; // offset=176B, size=16B 
            public ZEquipment_AxisManualVelocityComPublish Velocity; // offset=192B, size=16B 
            public ZEquipment_AxisManualPositionComPublish Position; // offset=208B, size=24B 
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZApplication_ActuatorDigitalComPublish
        {
            public String256 Name; // offset=0B, size=256B 
            // union in C# have issues with marshaling
            public byte IsAtMinus; // offset=256B, size=1B 
            public byte IsAtPlus; // offset=257B, size=1B 
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 6)] public byte[] _pad0;
            public double Duration; // offset=264B, size=8B 
            public String81 MinusOutputName; // offset=272B, size=81B 
            public String81 PlusOutputName; // offset=353B, size=81B 
            public String81 MinusInputName; // offset=434B, size=81B 
            public String81 PlusInputName; // offset=515B, size=81B 
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)] public byte[] _pad1;
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZApplication_DigitalComPublish
        {
            public String256 Name; // offset=0B, size=256B 
            // union in C# have issues with marshaling
            public PLC.Enums.ZApplication_IoType IoType; // offset=256B, size=2B 
            public byte IsSimulated; // offset=258B, size=1B 
            public byte IsWriteable; // offset=259B, size=1B 
            public byte IsEnabled; // offset=260B, size=1B 
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 1)] public byte[] _pad0;
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct UselessBoxComPublishEquipment
        {
            public ZApplication_AxisComPublish TransportX; // offset=0B, size=232B 
            // union in C# have issues with marshaling
            public ZApplication_ActuatorDigitalComPublish CylinderY; // offset=232B, size=600B 
            public ZApplication_DigitalComPublish MagnetOn; // offset=832B, size=262B 
            public ZApplication_DigitalComPublish LimitSwitchLeft; // offset=1094B, size=262B 
            public ZApplication_DigitalComPublish LimitSwitchRight; // offset=1356B, size=262B 
            public ZApplication_DigitalComPublish ConveyorOn; // offset=1618B, size=262B 
            public ZApplication_DigitalComPublish CylinderYIsDown; // offset=1880B, size=262B 
            public ZApplication_DigitalComPublish CylinderYIsUp; // offset=2142B, size=262B 
            public ZApplication_DigitalComPublish CylinderYMoveDown; // offset=2404B, size=262B 
            public ZApplication_DigitalComPublish CylinderYMoveUp; // offset=2666B, size=262B 
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct UselessBoxComPublish
        {
            public PLC.Enums.ZApplication_UnitStateMachineState State; // offset=0B, size=2B   -  state the unit is in 
            // union in C# have issues with marshaling
            public UselessBoxComRequest Request; // offset=2B, size=3B   -  booleans that indictate which action is currently possible to perform with this unit 
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 3)] public byte[] _pad0;
            public UselessBoxComPublishEquipment Equipment; // offset=8B, size=2928B   -  structs for equipment objects which are used by the bridges 
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZEquipment_AxisManualBaseFunctionComSubscribe
        {
            public byte EnableDrive; // offset=0B, size=1B 
            // union in C# have issues with marshaling
            public byte DisableDrive; // offset=1B, size=1B 
            public byte Stop; // offset=2B, size=1B 
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZEquipment_AxisManualHomingComSubscribe
        {
            public byte Homing; // offset=0B, size=1B 
            // union in C# have issues with marshaling
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZEquipment_AxisManualVelocityComSubscribe
        {
            public double Velocity; // offset=0B, size=8B 
            // union in C# have issues with marshaling
            public byte MoveVelocity; // offset=8B, size=1B 
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 7)] public byte[] _pad0;
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZEquipment_AxisManualPositionComSubscribe
        {
            public double Speed; // offset=0B, size=8B 
            // union in C# have issues with marshaling
            public double Position1; // offset=8B, size=8B 
            public byte MoveAbsolute1; // offset=16B, size=1B 
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 7)] public byte[] _pad0;
            public double Position2; // offset=24B, size=8B 
            public byte MoveAbsolute2; // offset=32B, size=1B 
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 7)] public byte[] _pad1;
            public double Delay; // offset=40B, size=8B 
            public byte MoveContinuous; // offset=48B, size=1B 
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 7)] public byte[] _pad2;
            public double Distance; // offset=56B, size=8B 
            public byte MoveRelative; // offset=64B, size=1B 
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 7)] public byte[] _pad3;
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZApplication_AxisComSubscribe
        {
            public ZEquipment_AxisManualBaseFunctionComSubscribe Base; // offset=0B, size=3B 
            // union in C# have issues with marshaling
            public ZEquipment_AxisManualHomingComSubscribe Homing; // offset=3B, size=1B 
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)] public byte[] _pad0;
            public ZEquipment_AxisManualVelocityComSubscribe Velocity; // offset=8B, size=16B 
            public ZEquipment_AxisManualPositionComSubscribe Position; // offset=24B, size=72B 
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZApplication_ActuatorDigitalComSubscribe
        {
            public byte MovePlus; // offset=0B, size=1B 
            // union in C# have issues with marshaling
            public byte MoveMinus; // offset=1B, size=1B 
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZApplication_DigitalComSubscribe
        {
            public byte Write; // offset=0B, size=1B 
            // union in C# have issues with marshaling
            public byte Enable; // offset=1B, size=1B 
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct UselessBoxComSubscribeEquipment
        {
            public ZApplication_AxisComSubscribe TransportX; // offset=0B, size=96B 
            // union in C# have issues with marshaling
            public ZApplication_ActuatorDigitalComSubscribe CylinderY; // offset=96B, size=2B 
            public ZApplication_DigitalComSubscribe MagnetOn; // offset=98B, size=2B 
            public ZApplication_DigitalComSubscribe LimitSwitchLeft; // offset=100B, size=2B 
            public ZApplication_DigitalComSubscribe LimitSwitchRight; // offset=102B, size=2B 
            public ZApplication_DigitalComSubscribe ConveyorOn; // offset=104B, size=2B 
            public ZApplication_DigitalComSubscribe CylinderYIsDown; // offset=106B, size=2B 
            public ZApplication_DigitalComSubscribe CylinderYIsUp; // offset=108B, size=2B 
            public ZApplication_DigitalComSubscribe CylinderYMoveDown; // offset=110B, size=2B 
            public ZApplication_DigitalComSubscribe CylinderYMoveUp; // offset=112B, size=2B 
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 6)] public byte[] _pad0;
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct UselessBoxComSubscribe
        {
            public UselessBoxComRequest Request; // offset=0B, size=3B   -  contains booleans that are used to start a specific sequence. 
            // union in C# have issues with marshaling
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 5)] public byte[] _pad0;
            public UselessBoxComSubscribeEquipment Equipment; // offset=8B, size=120B   -  structs for equipment objects which are used by the bridges 
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct UselessBoxCom
        {
            public UselessBoxComPublish Publish; // offset=0B, size=2936B 
            // union in C# have issues with marshaling
            public UselessBoxComSubscribe Subscribe; // offset=2936B, size=128B 
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZAux_LogEntry
        {
            public ulong TimeStamp; // offset=0B, size=8B 
            // union in C# have issues with marshaling
            public String256 Text; // offset=8B, size=256B  -  Unix timestamp of the running PLC target in 1ms resolution 
            public PLC.Enums.ZCore_LogLevel LogLevel; // offset=264B, size=2B   -  Message as string 
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 6)] public byte[] _pad0;
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZApplication_AlarmingMessageCom
        {
            public ZAux_LogEntry Extend; // offset=0B, size=272B 
            // union in C# have issues with marshaling
            public String256 Source; // offset=272B, size=256B 
            public PLC.Enums.ZApplication_AlarmingState State; // offset=528B, size=2B 
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 6)] public byte[] _pad0;
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZApplication_AlarmingComPublish
        {
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 11)] public ZApplication_AlarmingMessageCom[] Buffer;
            // union in C# have issues with marshaling
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZApplication_AlarmingAcknowledge
        {
            public byte Acknowledge; // offset=0B, size=1B 
            // union in C# have issues with marshaling
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZApplication_AlarmingComSubscribe
        {
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 11)] public ZApplication_AlarmingAcknowledge[] Buffer;
            // union in C# have issues with marshaling
            public byte Clear; // offset=11B, size=1B  -  set to true to remove all acknowledged messages 
        };
         
        [StructLayout(LayoutKind.Sequential, Pack=8)]        
        public struct ZApplication_AlarmingCom
        {
            public ZApplication_AlarmingComPublish Publish; // offset=0B, size=5896B 
            // union in C# have issues with marshaling
            public ZApplication_AlarmingComSubscribe Subscribe; // offset=5896B, size=12B 
            [MarshalAs(UnmanagedType.ByValArray, SizeConst = 4)] public byte[] _pad0;
        };
        
    }
}